### ISSUE TITLE
Demo Screenings

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#116]
at least 10 movies for 2 Month ahead

**Comment by christian-bettermann** [comment]
Updated screenings for all movies that we already had. Added about 4 movies with screenings.

**Comment by christian-bettermann** [comment]
deleted all tickets

**Comment by christian-bettermann** [comment]
deleted sync path

**Comment by HeroPhil** [comment]
remove carrot movies

**Comment by christian-bettermann** [comment]
All set and done 🎆

**Comment by christian-bettermann** [comment]
Had to delete all tickets again, to prevent embarrassing problems with tickets for movies that don't exist anymore while presenting 💠

**Comment by HeroPhil** [comment]
alright looks good:)
