### ISSUE TITLE
Fix: getScreeningsOfMovieByID()

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#12]
not working with until parameter.

Currently Frontend uses get all Screenings

**Comment by christian-bettermann** [comment]
Have tried this again, seems to be working. Please make another test.
I have only **rearranged the filter statements** and **added nines to the default until value** in the method header. The default value was somewhere in 2001 before I changed it.

**Comment by HeroPhil** [comment]
requires parameter until to be working. Default not functional?

**Comment by christian-bettermann** [comment]
new default for until was missing in index.ts (was defaulted to 0)
