### ISSUE TITLE
Can´t print all tickets if book whole hall

### ISSUE THREAD

**Issue by MichaelKaiser1** [HeroPhil/DHBW-KinoCinema#120]
first 10 or more tickets are ok but the other one are cutted

**Comment by MichaelKaiser1** [comment]
![image](https://user-images.githubusercontent.com/57496403/107075633-aac55780-67ea-11eb-936a-4fdcec467ac8.png)

**Comment by HeroPhil** [comment]
looks good

**Comment by MichaelKaiser1** [comment]
tickets itself looks good but every tickets have the same row and seat
requested review by someone else @ALL

**Comment by MichaelKaiser1** [comment]
![image](https://user-images.githubusercontent.com/57496403/107146026-d446c600-6945-11eb-9da2-2ececfe23b87.png)

**Comment by HeroPhil** [comment]
@ChrisDHBW ?!

**Comment by HeroPhil** [comment]
@ChrisDHBW ?!

**Comment by MichaelKaiser1** [comment]
Zusammenhang zwischen Abschneiden der Tickets und falschen Ticketinformationen.
Wird bewusst so gelassen. Fix für nächsten Release geplant.
bis zu 14 Tickets sieht gut aus

**Comment by HeroPhil** [comment]
guter Kompromiss
