### ISSUE TITLE
Testing: Unittesting of Cloudfunctions

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#14]
Automated Testing of backend Cloudfunctions.
Either stubed functions or isolated logic only

**Comment by HeroPhil** [comment]
@christian-bettermann please review tests

**Comment by NicklasPlatz** [comment]
Tests for 
checkIfAnyLogin 
countRowsOfScreening 
createEmptyHallSeatArray 
markSeatAsOccupied 
checkIfSeatIsValidInScreening 
are tested for all necessary scenarios
