### ISSUE TITLE
Create function: getTicketByID()

### ISSUE THREAD

**Issue by christian-bettermann** [HeroPhil/DHBW-KinoCinema#19]
* return ticket (with resolveRefs)
* no resolveRef for the user (only return userID)

**Comment by christian-bettermann** [comment]
resolveRefs Funktion für den User ist nicht sinnvoll. Bei dem Ticket wird nur die userID zurückgegeben.

**Comment by HeroPhil** [comment]
Looks good.

Error Messages could be returned in error object? Otherwise client might expect object data.{someTicketStuff} instead receives string data.
Applies to all functions.

Did some eslint fixes. Relocated await keyword.

**Comment by christian-bettermann** [comment]
Included error messages
