### ISSUE TITLE
Add Push Notifications to update seating plan

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#22]
While user is in screening seating overview, he should receive updates if booked seats array changes

**Comment by christian-bettermann** [comment]
Isn't this a frontend issue? They could simply refresh the seats every x seconds with a newly send request. 
Or what is the idea behind this?

**Comment by HeroPhil** [comment]
frontend could subscribe to changes in DB, otherwise CF would be called over and over again
