### ISSUE TITLE
Populate Categories of Movies on HomePage

### ISSUE THREAD

**Issue by NicklasPlatz** [HeroPhil/DHBW-KinoCinema#31]
The Movie Categories on the index page are not populated with movies.

- [x] Nicklas + Michael: create Movie object dummy

- [x] Christoph: create Movie objects with data from database

- [x] Christian + Philip: add category to movies in database and create "getMoviesByCategory()"

**Comment by christian-bettermann** [comment]
* Movies now have a category in the database (categorys are simple strings, no reference)
* Backend-functions implemented
* For informations about the usage of this function read the documentation (Wiki/Backend-functions & Wiki/Data-model updated)

**Comment by HeroPhil** [comment]
Can a movie have multiple categories?

**Comment by HeroPhil** [comment]
@christian-bettermann @HeroPhil working on it

**Comment by HeroPhil** [comment]
Categories will now be stored as String[]

**Comment by christian-bettermann** [comment]
- [x] revision getMoviesByCategory()
- [x] getAllCategories
- [x] Trigger on movie Collection: determineAllCategories()

**Comment by NicklasPlatz** [comment]
-reviewed
