### ISSUE TITLE
Review getMoviesByCategory()

### ISSUE THREAD

**Issue by christian-bettermann** [HeroPhil/DHBW-KinoCinema#36]
Please review the backend function getMoviesByCategory() as described in this issue https://github.com/HeroPhil/DHBW-KinoCinema/issues/31

**Comment by HeroPhil** [comment]
Looks good.

Is an ordering prior of using limit required? (as in basics.ts:42 getCollectionByIDLimitAmount() )

**Comment by christian-bettermann** [comment]
Implemented an ordering by priority.
