### ISSUE TITLE
create / edit movies function

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#42]
- [x] create function
- [x] edit function

**Comment by christian-bettermann** [comment]
Done. Ready for review. Documentation was updated 🐎

**Comment by HeroPhil** [comment]
Review:
add function ok.
update function: why using promises array? only one entry?

**Comment by christian-bettermann** [comment]
Included requested changes from review. Removed promises array. 🌊

**Comment by HeroPhil** [comment]
looks good:)
