### ISSUE TITLE
create / edit Screenings function

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#43]
- [x] create function

- [x] edit function

recurrences?

**Comment by HeroPhil** [comment]
recurrency?

**Comment by HeroPhil** [comment]
create(
  movieID,
  hallID,
  price,
  startTime (ms since 01-01-1970),
  repetetion (5 times),
  increments (weekly)
)

edit (
  screeningID,
  { all changes }
)

**Comment by christian-bettermann** [comment]
The functions are live now.
Documentation will follow soon

**Comment by HeroPhil** [comment]
Review:
overall: please adopt to new error handling standards.
add: questionable use of promises and await. Lets discuss together.
update: no need for promise arrays

**Comment by christian-bettermann** [comment]
Documentation done

**Comment by christian-bettermann** [comment]
Included requested changes from the review. 🌾 
To do: Discuss following point from review
> "add: questionable use of promises and await. Lets discuss together."

**Comment by HeroPhil** [comment]
looks good:)
