### ISSUE TITLE
Fix Error throwing

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#59]
Throw error like
{
   normalStuff: {...}
   error: {
      message: ""
   }
}

- [x] change CF
- [x] change CF Test
-  integreate in Frontend (other Issue)

**Comment by christian-bettermann** [comment]
To do: Discuss about return statements. Error is now returned like this:
```
{
     data: {
          error: {
               message: "xx"
          }
     }
}
```

**Comment by christian-bettermann** [comment]
* Fixed error throwing for all cloud functions
* ToDo: @HeroPhil implement in unit testing

**Comment by HeroPhil** [comment]
CF Testing didnt require any changes.
Looks good:)
Only frontend need to adopt to this style (other issue)
is this already documented @christian-bettermann ? If so issue may be closed

**Comment by christian-bettermann** [comment]
Errors are now live in documentation 🦘
