### ISSUE TITLE
User Sign In Status

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#64]
Some indicators that the user is signed in

**Comment by ChrisDHBW** [comment]
Im sessionstorage ist nun ein Attribut LoggedIn, dass out oder in zurückliefert. Abhängig davon kann das Icon, dann geändert werden

**Comment by HeroPhil** [comment]
add some indicator to navbar next to account button

**Comment by MichaelKaiser1** [comment]
looks good from frontend side

**Comment by christian-bettermann** [comment]
this is done
