### ISSUE TITLE
CF to read and write user information

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#65]
does what it sounds like

**Comment by HeroPhil** [comment]
please document as you review:) <3

**Comment by christian-bettermann** [comment]
* data of the type Interface userInformation that is written to the db should be in english only ("vorname" => "firstName" ...)
* editInformationOfUserByID() doesn't work => You have to provide a documentPath as the attribute for the update operation (It's just the uid and not the full path right now)
* the user shouldn't be able to write nonsense in his profile. We should only write certain keys to the db (not the whole newData object) => open for debate

**Comment by christian-bettermann** [comment]
functions will be documented quickly after fix

**Comment by HeroPhil** [comment]
interface should limit user ability to write anything to database

**Comment by HeroPhil** [comment]
only doc required @christian-bettermann ?

**Comment by christian-bettermann** [comment]
* Couldn't get editInformationOfUserByID() to work, please test (Might be my mistake 🎃)
* Added a first entry for these functions in our cloud functions documentation

**Comment by HeroPhil** [comment]
functions is called updateInformationOfUserByID
