### ISSUE TITLE
include personae / USmap etc..

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#71]
i old stuff in doc

**Comment by HeroPhil** [comment]
added the mutex one,
looks good, @NicklasPlatz need to select a few to be added in final presentation

**Comment by MichaelKaiser1** [comment]
added to presentation ones look good to me
again review by @HeroPhil requested

**Comment by HeroPhil** [comment]
still missing in "final" presentation in drive. please add @NicklasPlatz .

**Comment by HeroPhil** [comment]
othwise selction looks good

**Comment by HeroPhil** [comment]
looks good:)
