### ISSUE TITLE
doc backend Unittests

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#72]
as it says

**Comment by HeroPhil** [comment]
@christian-bettermann keep the database test in?

**Comment by christian-bettermann** [comment]
No need to test. You can leave them out / delete them. They aren't documented neither.

**Comment by HeroPhil** [comment]
maybe mention them...

**Comment by christian-bettermann** [comment]
mentioned them in Backend documentation

**Comment by HeroPhil** [comment]
expanded a bit.
please review again @christian-bettermann

**Comment by christian-bettermann** [comment]
Looks good to me!
