### ISSUE TITLE
Bug QRCode

### ISSUE THREAD

**Issue by ChrisDHBW** [HeroPhil/DHBW-KinoCinema#80]

**Comment by ChrisDHBW** [comment]
Wenn man mehr als einen QR Code erzeugen möchte kommt ein Fehler.

**Comment by NicklasPlatz** [comment]
Habe QRCodes mit Hilfe von Dummy Daten in der Methode erzeugen lassen und keine Probleme/Fehler feststellen können. Sowohl Tickets als auch unterschiedliche, funktionierende QRCodes wurden erzeugt ohne Fehlermeldung. Das Problem liegt wahrscheinlich bei den Daten. Die Fehlermeldung wäre dafür ganz hilfreich.

**Comment by ChrisDHBW** [comment]
QR8bitByte http://localhost:5000/confirmation/QRcode/qrcode.js:35
    addData http://localhost:5000/confirmation/QRcode/qrcode.js:87
    makeCode http://localhost:5000/confirmation/QRcode/qrcode.js:583
    createQrCode http://localhost:5000/confirmation/index.js:127
    createTicket http://localhost:5000/confirmation/index.js:113
    loadTicketsWithQRCode http://localhost:5000/confirmation/index.js:63
    onclick http://localhost:5000/confirmation/:1
Wie gesagt mit einem geht es, nur einer mehr bringt einem diesen Fehler

**Comment by NicklasPlatz** [comment]
Fehler konnte auf live Page reproduziert werden
![Bild_2021-01-28_130638](https://user-images.githubusercontent.com/57496386/106136529-b9b46600-6169-11eb-85e0-054971c12c47.png)
versucht wurden 3 Tickets zu buchen, nur das erste wurde erfolgreich erstellt, die anderen beiden sind "null" im SessionStorage
Fehler kommt daher das auf die "length" der QRCode Value Daten zugegriffen wird (im Prinzip eine NullPointerException)

**Comment by ChrisDHBW** [comment]
Bei mir steht da nichts mit length, bei mir steht da "Uncaught TypeError: this.data is undefined".
Hab das mit dem Length, aber präventiv behoben

**Comment by HeroPhil** [comment]
review:
- [x] load directly

**Comment by HeroPhil** [comment]
looks good
