### ISSUE TITLE
add / update halls

### ISSUE THREAD

**Issue by HeroPhil** [HeroPhil/DHBW-KinoCinema#85]
add / update halls functions

**Comment by HeroPhil** [comment]
no need for update function, functionality is not further pursued.

**Comment by christian-bettermann** [comment]
Function looks good so far, minor changes:
* add resolveRefs() on return statement so I see which rowtypes I added (right now I only handle with indexes for rowtypes but never see if it was the right one)
* name for hall should be required => default to undefined + error handle undefined hall name
* implement further error handling => was able to create a hall with rowtypes of "live/infastructure/rowtypes/undefined" while testing

**Comment by christian-bettermann** [comment]
* add documentation after revision

**Comment by HeroPhil** [comment]
disregard error handling
