### ISSUE TITLE
Search Page functionality

### ISSUE THREAD

**Issue by NicklasPlatz** [HeroPhil/DHBW-KinoCinema#91]
get search page to a usable state

**Comment by ChrisDHBW** [comment]
Funktionalität ist da und Dropdowngerüst auch, braucht nur noch etwas Styling.

**Comment by HeroPhil** [comment]
please adopt styling from index css for movie containers

**Comment by christian-bettermann** [comment]
* Is it possible to implement the exact style from the index page for the single films? The covers look deformed.
* Implement sorting function toogle (ascending & descending) for rating and playtime like you did for names.

**Comment by HeroPhil** [comment]
first worked totally fine yesterday, what happend @ChrisDHBW ??

**Comment by christian-bettermann** [comment]
* add focus on search button after typing a movie name in search field, so I can search on pressing enter

**Comment by HeroPhil** [comment]
some minor glitches, good enough
